# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    json_schema:
        class: JsonSchema\Validator
    
    json_validator:
        class: Yuido\JsonValidator\JsonValidator
        arguments: ["@json_schema"]
        
    rest_rpc:
        class: Yuido\RestRpcBundle\RestRpc
        arguments:
            - "@translator"
            - "@json_validator"
            - "%json_schemas_dir%"
            - "%debug%"
    
    schema_manager:
        class: Yuido\RestRpcBundle\SchemaManager
        arguments:
            - "@database_connection"
            - "@rest_rpc"